List<Map> courts = [
  {
    "courtName": "Supreme and High Courts",
    "courtNick": "all_courts",
  },
  {"courtName": "Supreme Court of India", "courtNick": "supremecourt"},
  // {"courtName": "Supreme Court - Daily Orders", "courtNick": "scorders"},
  {"courtName": "Allahabad High Court", "courtNick": "allahabad"},
  {"courtName": "Andhra Pradesh High Court", "courtNick": "andhra"},
  // {
  //   "courtName": "Andhra Pradesh High Court",
  //   "courtNick": "amravati",
  // },
  {"courtName": "Bombay High Court", "courtNick": "bombay"},
  {"courtName": "Calcutta High Court", "courtNick": "kolkata"},
  // {
  //   "courtName": "Calcutta High Court (Appellete Side)",
  //   "courtNick": "kolkata_app",
  // },
  {"courtName": "Chattisgarh High Court", "courtNick": "chattisgarh"},
  {"courtName": "Delhi High Court", "courtNick": "delhi"},
  // {"courtName": "Delhi High Court - Orders", "courtNick": "delhiorders"},
  {"courtName": "Gauhati High Court", "courtNick": "gauhati"},
  {"courtName": "Gujarat High Court", "courtNick": "gujarat"},
  {"courtName": "Himachal Pradesh High Court", "courtNick": "himachal_pradesh"},
  {"courtName": "Jammu & Kashmir High Court", "courtNick": "jammu"},
  // {
  //   "courtName": "Jammu & Kashmir High Court",
  //   "courtNick": "srinagar",
  // },
  {"courtName": "Jharkhand High Court", "courtNick": "jharkhand"},
  {"courtName": "Karnataka High Court", "courtNick": "karnataka"},
  {"courtName": "Kerala High Court", "courtNick": "kerala"},
  {"courtName": "Madhya Pradesh High Court", "courtNick": "madhyapradesh"},
  {"courtName": "Manipur High Court", "courtNick": "manipur"},
  {"courtName": "Meghalaya High Court", "courtNick": "meghalaya"},
  {"courtName": "Madras High Court", "courtNick": "chennai"},
  {"courtName": "Orissa High Court", "courtNick": "orissa"},
  {"courtName": "Patna High Court", "courtNick": "patna"},
  // {"courtName": "Patna High Court - Orders", "courtNick": "patna_orders"},
  {"courtName": "Punjab-Haryana High Court", "courtNick": "punjab"},
  {"courtName": "Rajasthan High Court - Jaipur", "courtNick": "jaipur"},
  // {"courtName": "Rajasthan High Court - Jodhpur", "courtNick": "jodhpur"},
  {"courtName": "Sikkim High Court", "courtNick": "sikkim"},
  {"courtName": "Uttarakhand High Court", "courtNick": "uttaranchal"},
  {"courtName": "Tripura High Court", "courtNick": "tripura"},
  {"courtName": "Telangana High Court", "courtNick": "telangana"},
  // {"courtName": "Delhi District Court", "courtNick": "delhidc"},
  // {"courtName": "Bangalore District Court", "courtNick": "bangaloredc"},
  // {"courtName": "Appellate Tribunal For Electricity", "courtNick": "aptel"},
  // {"courtName": "Authority Tribunal", "courtNick": "authority"},
  // {"courtName": "Central Administrative Tribunal", "courtNick": "cat"},
  // {"courtName": "Customs, Excise and Gold Tribunal", "courtNick": "cegat"},
  // {
  //   "courtName": "Central Electricity Regulatory Commission",
  //   "courtNick": "cerc",
  // },
  // {"courtName": "Central Information Commission", "courtNick": "cic"},
  // {"courtName": "Company Law Board", "courtNick": "clb"},
  // {"courtName": "Consumer Disputes Redressal", "courtNick": "consumer"},
  // {"courtName": "Copyright Board", "courtNick": "copyrightboard"},
  // {"courtName": "Debt Recovery Appellate Tribunal", "courtNick": "drat"},
  // {"courtName": "National Green Tribunal", "courtNick": "greentribunal"},
  // {"courtName": "Competition Commission of India", "courtNick": "cci"},
  // {"courtName": "Intellectual Property Appellate Board", "courtNick": "ipab"},
  // {"courtName": "Income Tax Appellate Tribunal", "courtNick": "itat"},
  // {
  //   "courtName": "Monopolies and Restrictive Trade Practices Commission",
  //   "courtNick": "mrtp",
  // },
  // {"courtName": "Securities Appellate Tribunal", "courtNick": "sebisat"},
  // {"courtName": "State Taxation Tribunal", "courtNick": "stt"},
  // {"courtName": "Telecom Disputes Settlement Tribunal", "courtNick": "tdsat"},
  // {"courtName": "Trademark Tribunal", "courtNick": "trademark"},
  // {"courtName": "Custom, Excise & Service Tax Tribunal", "courtNick": "cestat"},
  // {
  //   "courtName": "National Company Law Appellate Tribunal",
  //   "courtNick": "nclat",
  // },
];
