List<String> lawyerSpecializations = [
  "Criminal",
  "Civil",
  "Family",
  "Divorce",
  "Property",
  "Corporate",
  "Cyber Crime",
  "Consumer",
  "GST & Tax",
  "Labour & Employment",
  "Other",
];

List<String> lawyerExpertises = [
  "Legal Notice",
  "Agreement Drafting",
  "Document Verification",
  "Affidavit & Notary",
  "Property Verification",
  "Land Disputes",
  "Recovery Cases",
  "Cheque Bounce",
  "Bail Matters",
  "FIR & Police Complaints",
  "Consumer Complaints",
  "Motor Accident Claims",
  "Insurance Claims",
  "Employment Issues",
  "Wrongful Termination",
  "PF & Gratuity",
  "Income Tax Matters",
  "GST Matters",
  "Company Registration",
  "Contract Disputes",
  "Cyber Fraud",
  "Online Scam Cases",
  "RTI Filing",
  "Court Representation",
  "Legal Consultation",
  "Property Registration",
  "Sale Deed Drafting",
  "Rent Agreement",
  "Eviction Matters",
  "Housing Society Issues",
  "Builder Disputes",
  "RERA Complaints",
  "Will Drafting",
  "Inheritance Issues",
  "Succession Certificate",
  "Power of Attorney",
  "Marriage Registration",
  "Divorce Documentation",
  "Maintenance Cases",
  "Child Custody Issues",
  "Domestic Violence Cases",
  "Senior Citizen Issues",
  "Medical Negligence",
  "Defamation Cases",
  "Trademark Registration",
  "Copyright Issues",
  "Startup Legal Support",
  "Business Compliance",
  "Bank Loan Disputes",
  "Debt Recovery Tribunal (DRT)",
  "SARFAESI Matters",
  "Arbitration Matters",
  "Mediation Support",
];
