import 'package:flutter/material.dart';

List<Map> lawyers = [
  {
    "name": "Rajesh Sharma",
    "court": "Bombay High Court",
    "district": "Mumbai",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["White Collar Crime", "Bail & Appeals"],
    "shortIntro":
    "Experienced criminal defence lawyer with strong courtroom presence.",
    "detailedIntro":
    "Over 12 years handling serious criminal matters, appeals, and bail proceedings in metropolitan courts. Skilled in evidence assessment and trial strategy.",
  },
  {
    "name": "Priya Deshmukh",
    "court": "Family Court",
    "district": "Pune",
    "type": "Family Lawyer",
    "color": Colors.pink,
    "practiceArea": "Family Law",
    "otherPracticeAreas": ["Matrimonial Disputes", "Child Custody"],
    "shortIntro":
    "Compassionate family lawyer focused on amicable resolutions.",
    "detailedIntro":
    "Specialises in divorce, child custody, and maintenance cases with emphasis on negotiation and mediation. Experienced in sensitive family matters and counseling clients.",
  },
  {
    "name": "Amit Kulkarni",
    "court": "District Court",
    "district": "Nagpur",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil Litigation",
    "otherPracticeAreas": ["Contract Disputes", "Property Litigation"],
    "shortIntro":
    "Practical civil litigator skilled in district court procedure.",
    "detailedIntro":
    "Handles civil disputes including contract and property matters, with attention to evidence and procedural compliance. Focused on achieving timely client outcomes.",
  },
  {
    "name": "Neha Patil",
    "court": "Sessions Court",
    "district": "Thane",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Victim Representation", "Bail Matters"],
    "shortIntro": "Dedicated criminal lawyer with courtroom experience.",
    "detailedIntro":
    "Represents both defence and victim matters in sessions court, handling investigations, bail applications, and trials. Known for clear case preparation and advocacy.",
  },
  {
    "name": "Suresh Iyer",
    "court": "High Court",
    "district": "Chennai",
    "type": "Constitutional Lawyer",
    "color": Colors.cyan,
    "practiceArea": "Constitutional & Public Law",
    "otherPracticeAreas": ["Administrative Law", "Judicial Review"],
    "shortIntro": "Seasoned constitutional law practitioner in the High Court.",
    "detailedIntro":
    "Advises on fundamental rights, writ petitions, and administrative law matters. Extensive appellate experience and academic background in constitutional jurisprudence.",
  },
  {
    "name": "Kavita Joshi",
    "court": "District Court",
    "district": "Nashik",
    "type": "Property Lawyer",
    "color": Colors.orange,
    "practiceArea": "Property & Real Estate",
    "otherPracticeAreas": ["Title Disputes", "Land Registration"],
    "shortIntro": "Property law specialist handling civil property disputes.",
    "detailedIntro":
    "Assists clients with title issues, partition suits, and property transactions. Emphasises meticulous documentation and due diligence to prevent disputes.",
  },
  {
    "name": "Rohan Mehta",
    "court": "Commercial Court",
    "district": "Ahmedabad",
    "type": "Corporate Lawyer",
    "color": Colors.yellow,
    "practiceArea": "Corporate & Commercial Law",
    "otherPracticeAreas": ["Contract Drafting", "Insolvency Matters"],
    "shortIntro": "Corporate counsel focused on commercial litigation.",
    "detailedIntro":
    "Handles contractual disputes, corporate compliance, and commercial litigation in specialised courts. Advises startups and SMEs on transactional matters.",
  },
  {
    "name": "Anjali Verma",
    "court": "District Court",
    "district": "Indore",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil Litigation",
    "otherPracticeAreas": ["Family Property", "Consumer Disputes"],
    "shortIntro": "Reliable civil lawyer with client-focused approach.",
    "detailedIntro":
    "Represents clients in civil suits, consumer cases, and property matters. Prioritises cost-effective strategies and clear client communication.",
  },
  {
    "name": "Deepak Singh",
    "court": "District Court",
    "district": "Lucknow",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Investigation Support", "Plea Bargaining"],
    "shortIntro": "Criminal practitioner experienced in trial advocacy.",
    "detailedIntro":
    "Manages criminal defence from investigation through trial, with experience in forensic and evidentiary issues. Strong negotiation skills for settlements and pleas.",
  },
  {
    "name": "Pooja Mishra",
    "court": "Family Court",
    "district": "Kanpur",
    "type": "Family Lawyer",
    "color": Colors.pink,
    "practiceArea": "Family Law",
    "otherPracticeAreas": ["Adoption", "Maintenance Claims"],
    "shortIntro":
    "Family law attorney skilled in contested and uncontested matters.",
    "detailedIntro":
    "Guides clients through divorce, custody, and maintenance disputes, using mediation where possible. Provides empathetic support and clear legal advice.",
  },
  {
    "name": "Arjun Rao",
    "court": "High Court",
    "district": "Hyderabad",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil & Appellate Law",
    "otherPracticeAreas": ["Commercial Disputes", "Arbitration"],
    "shortIntro": "Appellate civil lawyer with High Court practice.",
    "detailedIntro":
    "Handles appeals, civil writs, and complex commercial litigation in the High Court. Advises on arbitration and alternate dispute resolution.",
  },
  {
    "name": "Sneha Nair",
    "court": "District Court",
    "district": "Kochi",
    "type": "Property Lawyer",
    "color": Colors.orange,
    "practiceArea": "Property & Conveyancing",
    "otherPracticeAreas": ["Lease Disputes", "Title Verification"],
    "shortIntro": "Property lawyer focusing on conveyancing and disputes.",
    "detailedIntro":
    "Provides transactional and litigation support for real estate matters, including drafting and title searches. Helps clients resolve landlord-tenant and title conflicts.",
  },
  {
    "name": "Manish Gupta",
    "court": "Sessions Court",
    "district": "Delhi",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Economic Offences", "Cybercrime"],
    "shortIntro": "High-energy criminal lawyer handling serious offences.",
    "detailedIntro":
    "Represents clients in sessions court for serious criminal charges, with experience in complex evidence and forensic issues. Strong trial record and client advocacy.",
  },
  {
    "name": "Ritu Malhotra",
    "court": "District Court",
    "district": "Gurgaon",
    "type": "Corporate Lawyer",
    "color": Colors.yellow,
    "practiceArea": "Corporate Law",
    "otherPracticeAreas": ["Mergers & Acquisitions", "Compliance"],
    "shortIntro": "Corporate counsel advising businesses on legal strategy.",
    "detailedIntro":
    "Advises companies on corporate governance, contracts, and regulatory compliance. Experienced in transactional work and dispute prevention.",
  },
  {
    "name": "Vinod Chavan",
    "court": "District Court",
    "district": "Aurangabad",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil Litigation",
    "otherPracticeAreas": ["Recovery Suits", "Execution"],
    "shortIntro": "Experienced in civil procedure and court practice.",
    "detailedIntro":
    "Handles a wide range of civil matters including recovery and execution proceedings. Strong knowledge of procedural law and drafting of pleadings.",
  },
  {
    "name": "Ayesha Khan",
    "court": "Family Court",
    "district": "Bhopal",
    "type": "Family Lawyer",
    "color": Colors.pink,
    "practiceArea": "Family Law",
    "otherPracticeAreas": ["Domestic Violence", "Guardianship"],
    "shortIntro": "Client-centered family law practitioner.",
    "detailedIntro":
    "Works on divorce, protection orders, and child-related disputes with sensitivity. Focuses on practical solutions and support for vulnerable clients.",
  },
  {
    "name": "Nitin Sawant",
    "court": "Sessions Court",
    "district": "Kolhapur",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Motor Offences", "Bail Applications"],
    "shortIntro": "Practitioner focused on efficient criminal case handling.",
    "detailedIntro":
    "Experienced in sessions court with emphasis on swift resolution of criminal matters. Advises clients during investigation and trial phases.",
  },
  {
    "name": "Karan Oberoi",
    "court": "High Court",
    "district": "Chandigarh",
    "type": "Constitutional Lawyer",
    "color": Colors.cyan,
    "practiceArea": "Constitutional & Administrative Law",
    "otherPracticeAreas": ["Service Law", "Public Interest Litigation"],
    "shortIntro": "High Court advocate specialising in public law.",
    "detailedIntro":
    "Handles writ petitions, service matters, and PILs with analytical legal reasoning. Experienced in appellate advocacy and policy-related litigation.",
  },
  {
    "name": "Meenal Jain",
    "court": "District Court",
    "district": "Jaipur",
    "type": "Property Lawyer",
    "color": Colors.orange,
    "practiceArea": "Real Estate Law",
    "otherPracticeAreas": ["Development Agreements", "Stamp Duty Issues"],
    "shortIntro":
    "Real estate lawyer advising on transactional and dispute matters.",
    "detailedIntro":
    "Advises clients on property transactions, compliance and dispute resolution. Ensures clear documentation and assists in court where needed.",
  },
  {
    "name": "Rahul Pandey",
    "court": "District Court",
    "district": "Prayagraj",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil Litigation",
    "otherPracticeAreas": ["Landlord-Tenant", "Consumer Law"],
    "shortIntro": "Practical civil advocate focused on client results.",
    "detailedIntro":
    "Handles a variety of civil matters with emphasis on efficient case management and settlement where appropriate. Experienced in drafting and hearings.",
  },
  {
    "name": "Shweta Kulkarni",
    "court": "Family Court",
    "district": "Satara",
    "type": "Family Lawyer",
    "color": Colors.pink,
    "practiceArea": "Family Law",
    "otherPracticeAreas": ["Prenuptial Agreements", "Mediation"],
    "shortIntro":
    "Family lawyer who favours mediation and negotiated settlements.",
    "detailedIntro":
    "Focuses on amicable dispute resolution in family matters, offering mediation services and litigation support when necessary. Prioritises client welfare and children’s interests.",
  },
  {
    "name": "Imran Siddiqui",
    "court": "Sessions Court",
    "district": "Bangalore",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Fraud", "Cybercrime"],
    "shortIntro":
    "Criminal defence lawyer with technology-related case experience.",
    "detailedIntro":
    "Handles cybercrime and fraud cases along with general criminal matters, collaborating with forensic experts. Strong cross-examination and evidence-management skills.",
  },
  {
    "name": "Sanjay Reddy",
    "court": "Commercial Court",
    "district": "Hyderabad",
    "type": "Corporate Lawyer",
    "color": Colors.yellow,
    "practiceArea": "Commercial & Corporate Law",
    "otherPracticeAreas": ["Arbitration", "Banking Litigation"],
    "shortIntro": "Commercial litigator representing businesses in disputes.",
    "detailedIntro":
    "Represents corporate clients in commercial litigation and arbitration, focusing on contract enforcement and recovery matters. Advises on dispute avoidance strategies.",
  },
  {
    "name": "Pallavi Desai",
    "court": "District Court",
    "district": "Surat",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil & Consumer Law",
    "otherPracticeAreas": ["Consumer Claims", "Property Disputes"],
    "shortIntro":
    "Civil advocate with experience in consumer protection matters.",
    "detailedIntro":
    "Assists clients with consumer court claims, civil suits, and property-related litigation. Emphasises client education and efficient resolution.",
  },
  {
    "name": "Ashok Yadav",
    "court": "District Court",
    "district": "Rewari",
    "type": "Property Lawyer",
    "color": Colors.orange,
    "practiceArea": "Property Law",
    "otherPracticeAreas": ["Partition Suits", "Boundary Disputes"],
    "shortIntro": "Property litigator handling local property disputes.",
    "detailedIntro":
    "Has extensive experience in partition, title and boundary disputes in district courts. Focused on practical remedies and clear pleadings.",
  },
  {
    "name": "Nisha Kapoor",
    "court": "Family Court",
    "district": "Amritsar",
    "type": "Family Lawyer",
    "color": Colors.pink,
    "practiceArea": "Family Law",
    "otherPracticeAreas": ["Domestic Violence", "Child Adoption"],
    "shortIntro": "Family law attorney offering empathetic representation.",
    "detailedIntro":
    "Works on sensitive family matters including protection orders and adoption, providing both legal and emotional support. Experienced in court advocacy and mediation.",
  },
  {
    "name": "Harish Menon",
    "court": "High Court",
    "district": "Ernakulam",
    "type": "Constitutional Lawyer",
    "color": Colors.cyan,
    "practiceArea": "Constitutional & Administrative Law",
    "otherPracticeAreas": ["Service Matters", "Environmental Law"],
    "shortIntro":
    "High Court counsel with public interest litigation experience.",
    "detailedIntro":
    "Handles writ petitions and public interest cases with a focus on administrative justice. Advises NGOs and individuals on regulatory compliance and constitutional issues.",
  },
  {
    "name": "Sunita Roy",
    "court": "District Court",
    "district": "Kolkata",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil Litigation",
    "otherPracticeAreas": ["Consumer Law", "Recovery"],
    "shortIntro": "Seasoned civil litigator with client-first approach.",
    "detailedIntro":
    "Represents clients in various civil disputes, prioritising practical and cost-effective solutions. Strong track record in consumer courts and recovery suits.",
  },
  {
    "name": "Prakash Jadhav",
    "court": "Sessions Court",
    "district": "Solapur",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Traffic & Motor Offences", "Bail"],
    "shortIntro":
    "Local criminal advocate experienced in sessions court matters.",
    "detailedIntro":
    "Handles criminal trials, bail applications, and plea processes with local courts. Known for pragmatic case management and client communication.",
  },
  {
    "name": "Tushar Bansal",
    "court": "Commercial Court",
    "district": "Noida",
    "type": "Corporate Lawyer",
    "color": Colors.yellow,
    "practiceArea": "Corporate & Commercial Law",
    "otherPracticeAreas": ["Contract Law", "Startups"],
    "shortIntro": "Corporate lawyer advising startups and enterprises.",
    "detailedIntro":
    "Provides counsel on contracts, corporate structuring, and commercial disputes. Experienced in transactional work and dispute resolution for growing businesses.",
  },
  {
    "name": "Farah Ali",
    "court": "District Court",
    "district": "Aligarh",
    "type": "Civil Lawyer",
    "color": Colors.blue,
    "practiceArea": "Civil Litigation",
    "otherPracticeAreas": ["Property Disputes", "Family Property"],
    "shortIntro": "Civil lawyer focused on property and family-related suits.",
    "detailedIntro":
    "Handles civil suits involving property and familial disputes, offering negotiation and litigation options. Emphasises thorough evidence collection.",
  },
  {
    "name": "Mohit Agarwal",
    "court": "High Court",
    "district": "Allahabad",
    "type": "Constitutional Lawyer",
    "color": Colors.cyan,
    "practiceArea": "Constitutional Law",
    "otherPracticeAreas": ["Service Law", "Election Law"],
    "shortIntro": "High Court advocate with breadth in public law matters.",
    "detailedIntro":
    "Represents clients in writ petitions and appellate matters, with experience in administrative and service law. Strong record in researched legal arguments.",
  },
  {
    "name": "Rekha Solanki",
    "court": "Family Court",
    "district": "Udaipur",
    "type": "Family Lawyer",
    "color": Colors.pink,
    "practiceArea": "Family Law",
    "otherPracticeAreas": ["Maintenance", "Custody"],
    "shortIntro": "Trusted family lawyer offering practical solutions.",
    "detailedIntro":
    "Assists clients in divorce, custody, and maintenance matters with a focus on settlements and child welfare. Experienced mediator and litigator.",
  },
  {
    "name": "Sameer Shaikh",
    "court": "Sessions Court",
    "district": "Malegaon",
    "type": "Criminal Lawyer",
    "color": Colors.green,
    "practiceArea": "Criminal Law",
    "otherPracticeAreas": ["Narcotics", "Economic Offences"],
    "shortIntro": "Criminal law specialist handling serious charges.",
    "detailedIntro":
    "Represents clients in sessions court for major criminal offences, coordinating with investigators and experts. Strong trial and cross-examination skills.",
  },
];