# Judgment API tests

# Fetch judgments by court name (and optional filters)
# Replace values as needed
GET http://localhost:3000/judgment/get_by_court?court_name=all_courts

# add additional query parameters:
# &from_date=1-1-2026&to_date=24-2-2026&options=mostrecent&search=contract
